"""Unit tests for the statement-aware document prescan (agent/derive.py).

The prescan routes the agent to the exhibit holding the financial statements.
It must detect all three statements (income, balance sheet, cash flow) — not
just the income statement — so multi-statement runs skip the expensive LLM
indexer only when the routed exhibit actually holds everything requested.
"""
from __future__ import annotations

import unittest

from earnings_agents.agent.derive import prescan_document
from earnings_agents.agent.pipeline import _hint_covers_targets


_IS_ONLY = """\
Condensed Consolidated Statements of Operations
Total net sales
Cost of sales
Gross margin
Operating income
Provision for income taxes
Net income
Earnings per share: Basic and diluted
"""

_BS_CF = """\
Condensed Consolidated Balance Sheets
Cash and cash equivalents
Marketable securities
Accounts receivable, net
Inventories
Property, plant and equipment, net
Total current assets
Total assets
Total current liabilities
Total liabilities
Retained earnings
Total shareholders' equity
Total liabilities and shareholders' equity

Condensed Consolidated Statements of Cash Flows
Cash generated by operating activities
Purchases of marketable securities
Proceeds from maturities of marketable securities
Payments for acquisition of property, plant and equipment
Cash used in investing activities
Payments for dividends and dividend equivalents
Repurchases of common stock
Cash used in financing activities
Increase/(decrease) in cash, cash equivalents and restricted cash
"""


def _doc_map_for(text: str, exhibit: str) -> list[dict]:
    return [{
        "exhibit": exhibit,
        "line_start": 1,
        "line_end": text.count("\n") + 1,
    }]


class TestPrescanStatements(unittest.TestCase):
    def test_detects_all_three_statements(self):
        text = _IS_ONLY + "\n" + _BS_CF
        _, _, hints = prescan_document(text, document_map=_doc_map_for(text, "EX-99.1"))
        self.assertIsNotNone(hints)
        self.assertEqual(len(hints), 1)
        h = hints[0]
        self.assertTrue(h["income"])
        self.assertTrue(h["balance_sheet"])
        self.assertTrue(h["cash_flow"])
        self.assertGreaterEqual(h["bs_count"], 3)
        self.assertGreaterEqual(h["cf_count"], 3)

    def test_detects_income_only_when_bs_cf_absent(self):
        _, _, hints = prescan_document(
            _IS_ONLY, document_map=_doc_map_for(_IS_ONLY, "EX-99.1")
        )
        self.assertIsNotNone(hints)
        h = hints[0]
        self.assertTrue(h["income"])
        self.assertFalse(h["balance_sheet"])
        self.assertFalse(h["cash_flow"])

    def test_no_document_map_returns_no_hints(self):
        _, _, hints = prescan_document(_IS_ONLY)
        self.assertIsNone(hints)

    def test_sorts_most_complete_exhibit_first(self):
        income_exhibit = _IS_ONLY
        full_exhibit = _IS_ONLY + "\n" + _BS_CF
        combined = (
            "=== EX-99.1 (income only) ===\n" + income_exhibit
            + "\n=== EX-99.2 (all three) ===\n" + full_exhibit
        )
        lines = combined.split("\n")
        doc_map = [
            {
                "exhibit": "EX-99.1",
                "line_start": 1,
                "line_end": len(("=== EX-99.1 (income only) ===\n" + income_exhibit).split("\n")),
            },
            {
                "exhibit": "EX-99.2",
                "line_start": len(("=== EX-99.1 (income only) ===\n" + income_exhibit).split("\n")) + 1,
                "line_end": len(lines),
            },
        ]
        _, _, hints = prescan_document(combined, document_map=doc_map)
        self.assertIsNotNone(hints)
        # EX-99.2 covers all three statements → must be first after sorting.
        self.assertEqual(hints[0]["exhibit"], "EX-99.2")


class TestHintCoversTargets(unittest.TestCase):
    def _hint(self, income=True, bs=True, cf=True):
        return {"income": income, "balance_sheet": bs, "cash_flow": cf}

    def test_all_three_targets_require_all_three_statements(self):
        self.assertTrue(_hint_covers_targets(self._hint(), ["income", "balancesheet", "cashflow"]))
        self.assertFalse(
            _hint_covers_targets(self._hint(cf=False), ["income", "balancesheet", "cashflow"])
        )
        self.assertFalse(
            _hint_covers_targets(self._hint(bs=False), ["income", "balancesheet", "cashflow"])
        )

    def test_income_only_target(self):
        self.assertTrue(_hint_covers_targets(self._hint(), ["income"]))
        self.assertTrue(_hint_covers_targets(self._hint(bs=False, cf=False), ["income"]))

    def test_balancesheet_and_cashflow_target(self):
        self.assertTrue(
            _hint_covers_targets(self._hint(income=False), ["balancesheet", "cashflow"])
        )
        self.assertFalse(
            _hint_covers_targets(self._hint(income=False, cf=False), ["balancesheet", "cashflow"])
        )


if __name__ == "__main__":
    unittest.main()
