"""Unit tests for cash-flow YTD de-accumulation (agent/deaccumulate.py)."""
from __future__ import annotations

import unittest
from unittest import mock

from earnings_agents.agent.deaccumulate import (
    classify_cashflow_kind,
    deaccumulate_cashflow_value,
    detect_cashflow_period_basis,
    detect_cashflow_statement_basis,
    resolve_cashflow_concept,
)
from earnings_agents.agent.tools import build_pi_tools
import earnings_agents.agent.pipeline as pipeline_module


def _cf(_id, concept, label=None, statement_type="cashflow"):
    return {
        "_id": _id,
        "concept": concept,
        "taxonomy_key": concept,
        "label": label or concept,
        "statement_type": statement_type,
    }


CF_CONCEPTS = [
    _cf("cf1", "us-gaap:NetCashProvidedByUsedInOperatingActivities",
        "Net cash provided by operating activities"),
    _cf("cf2", "us-gaap:PaymentsToAcquirePropertyPlantAndEquipment",
        "Payments to acquire property, plant and equipment"),
    _cf("cf3", "us-gaap:CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents",
        "Cash, cash equivalents, restricted cash, and restricted cash equivalents"),
    _cf("bs1", "us-gaap:CashAndCashEquivalentsAtCarryingValue",
        "Cash and cash equivalents at carrying value", statement_type="balancesheet"),
]


class TestClassifyKind(unittest.TestCase):
    def test_flow(self):
        self.assertEqual(classify_cashflow_kind(
            "NetCashProvidedByUsedInOperatingActivities",
            "Net cash provided by operating activities",
            "Cash generated by operating activities"), "flow")

    def test_ending_via_filing_label(self):
        self.assertEqual(classify_cashflow_kind(
            "CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents",
            "Cash, cash equivalents, restricted cash, and restricted cash equivalents",
            "Cash, cash equivalents and restricted cash, ending balances"), "ending")

    def test_beginning_via_filing_label(self):
        self.assertEqual(classify_cashflow_kind(
            "CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents",
            "Cash, cash equivalents, restricted cash, and restricted cash equivalents",
            "Cash, cash equivalents and restricted cash, beginning balances"), "beginning")

    def test_ending_via_concept_name(self):
        self.assertEqual(classify_cashflow_kind(
            "CashAndCashEquivalentsEndingBalance", ""), "ending")

    def test_beginning_via_concept_name(self):
        self.assertEqual(classify_cashflow_kind(
            "CashAndCashEquivalentsBeginningBalance", ""), "beginning")

    def test_cash_snapshot_without_filing_label(self):
        self.assertEqual(classify_cashflow_kind(
            "us-gaap:CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents",
            "Cash, Cash Equivalent, Restricted Cash, and Restricted Cash Equivalent, Continuing Operation"), "ending")

    def test_cash_flow_period_increase_decrease(self):
        self.assertEqual(classify_cashflow_kind(
            "us-gaap:CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsPeriodIncreaseDecreaseIncludingExchangeRateEffect",
            "Cash, Cash Equivalent, Period Increase (Decrease)"), "flow")


class TestDetectBasis(unittest.TestCase):
    def test_quarterly(self):
        out = detect_cashflow_period_basis("CONDENSED STATEMENTS OF CASH FLOWS\nThree Months Ended March 28, 2026")
        self.assertEqual([f["basis"] for f in out], ["quarterly"])

    def test_ytd_6m(self):
        out = detect_cashflow_period_basis("Six Months Ended March 28, 2026")
        self.assertEqual([f["basis"] for f in out], ["ytd_6m"])

    def test_ytd_9m(self):
        out = detect_cashflow_period_basis("Nine Months Ended June 27, 2026")
        self.assertEqual([f["basis"] for f in out], ["ytd_9m"])

    def test_annual(self):
        out = detect_cashflow_period_basis("Fiscal Year Ended September 27, 2026")
        self.assertEqual([f["basis"] for f in out], ["annual"])

    def test_multiple_bases_in_order(self):
        out = detect_cashflow_period_basis(
            "Three Months Ended X\nNine Months Ended Y\nSix Months Ended Z"
        )
        self.assertEqual([f["basis"] for f in out], ["quarterly", "ytd_6m", "ytd_9m"])


class TestDetectCashflowStatementBasis(unittest.TestCase):
    def test_finds_cashflow_ytd_ignoring_income_columns(self):
        text = (
            "CONDENSED CONSOLIDATED STATEMENTS OF OPERATIONS (Unaudited)\n"
            "Three Months Ended June 27, 2026\n"
            "Nine Months Ended June 27, 2026\n"
            "Total net sales 109,417\n\n"
            "CONDENSED CONSOLIDATED STATEMENTS OF CASH FLOWS (Unaudited)\n"
            "(In millions)\n"
            "Nine Months Ended June 27, 2026\n"
        )
        b = detect_cashflow_statement_basis(text)
        self.assertIsNotNone(b)
        self.assertEqual(b["basis"], "ytd_9m")

    def test_quarterly_cashflow(self):
        text = (
            "CONDENSED CONSOLIDATED STATEMENTS OF CASH FLOWS (Unaudited)\n"
            "(In millions)\n"
            "Three Months Ended June 27, 2026\n"
        )
        b = detect_cashflow_statement_basis(text)
        self.assertEqual(b["basis"], "quarterly")

    def test_no_cashflow_returns_none(self):
        self.assertIsNone(detect_cashflow_statement_basis("just an income statement"))


class TestResolveConcept(unittest.TestCase):
    def test_resolves_bracketed_key(self):
        c = resolve_cashflow_concept(
            "[us-gaap:PaymentsToAcquirePropertyPlantAndEquipment]", CF_CONCEPTS
        )
        self.assertIsNotNone(c)
        self.assertEqual(c["_id"], "cf2")

    def test_resolves_bare_key(self):
        c = resolve_cashflow_concept(
            "us-gaap:NetCashProvidedByUsedInOperatingActivities", CF_CONCEPTS
        )
        self.assertEqual(c["_id"], "cf1")

    def test_excludes_non_cashflow(self):
        c = resolve_cashflow_concept(
            "[us-gaap:CashAndCashEquivalentsAtCarryingValue]", CF_CONCEPTS
        )
        self.assertIsNone(c)

    def test_unknown_returns_none(self):
        self.assertIsNone(resolve_cashflow_concept("[us-gaap:Nope]", CF_CONCEPTS))


class TestDeaccumulateValue(unittest.TestCase):
    def _run(self, value, concept_key, quarter, ytd_months, filing_label="", priors=None):
        with mock.patch(
            "earnings_agents.agent.deaccumulate.load_prior_quarter_values",
            return_value=priors or {},
        ):
            return deaccumulate_cashflow_value(
                cik="0000320193",
                value=value,
                concept_key=concept_key,
                fiscal_year=2026,
                quarter=quarter,
                ytd_months=ytd_months,
                target_concepts=CF_CONCEPTS,
                filing_label=filing_label,
            )

    def test_q2_flow_deaccumulates(self):
        out = self._run(60000, "[us-gaap:NetCashProvidedByUsedInOperatingActivities]",
                        quarter=2, ytd_months=6, priors={1: 28000.0})
        self.assertIn("32,000", out)  # 60000 - 28000
        self.assertIn("__derived__", out)

    def test_q3_flow_deaccumulates(self):
        out = self._run(116996, "[us-gaap:NetCashProvidedByUsedInOperatingActivities]",
                        quarter=3, ytd_months=9, priors={1: 41000.0, 2: 34000.0})
        self.assertIn("41,996", out)  # 116996 - 75000

    def test_q1_is_noop(self):
        out = self._run(28000, "[us-gaap:NetCashProvidedByUsedInOperatingActivities]",
                        quarter=1, ytd_months=3)
        self.assertIn("No de-accumulation needed", out)

    def test_ytd_months_mismatch(self):
        out = self._run(60000, "[us-gaap:NetCashProvidedByUsedInOperatingActivities]",
                        quarter=2, ytd_months=9)
        self.assertIn("does not match quarter", out)

    def test_ending_snapshot_as_is(self):
        out = self._run(
            36100,
            "[us-gaap:CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents]",
            quarter=3, ytd_months=9,
            filing_label="Cash, cash equivalents and restricted cash, ending balances",
        )
        self.assertIn("AS-IS", out)
        self.assertNotIn("De-accumulated", out)

    def test_beginning_snapshot_skip(self):
        out = self._run(
            30100,
            "[us-gaap:CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents]",
            quarter=3, ytd_months=9,
            filing_label="Cash, cash equivalents and restricted cash, beginning balances",
        )
        self.assertIn("SKIP", out)

    def test_missing_prior_quarter(self):
        out = self._run(60000, "[us-gaap:NetCashProvidedByUsedInOperatingActivities]",
                        quarter=2, ytd_months=6, priors={})
        self.assertIn("missing prior quarter", out)

    def test_unknown_concept(self):
        out = self._run(100, "[us-gaap:Nope]", quarter=2, ytd_months=6)
        self.assertIn("map_concept()", out)


class TestVerifyForcesDeaccumulation(unittest.TestCase):
    """verify_cash_flow_identity must REFUSE a YTD cash-flow statement until
    the agent has de-accumulated at least one flow row (forcing function)."""

    def _tools(self):
        text = (
            "CONDENSED CONSOLIDATED STATEMENTS OF OPERATIONS (Unaudited)\n"
            "Three Months Ended June 27, 2026\n"
            "Nine Months Ended June 27, 2026\n"
            "Total net sales 109,417\n\n"
            "CONDENSED CONSOLIDATED STATEMENTS OF CASH FLOWS (Unaudited)\n"
            "(In millions)\n"
            "Nine Months Ended June 27, 2026\n"
            "Cash generated by operating activities 116,996\n"
        )
        targets = [
            {
                "_id": "c1",
                "concept": "us-gaap:NetCashProvidedByUsedInOperatingActivities",
                "taxonomy_key": "us-gaap:NetCashProvidedByUsedInOperatingActivities",
                "label": "Net cash provided by operating activities",
                "statement_type": "cashflow",
            }
        ]
        return build_pi_tools(
            text, {}, fiscal_year=2026, quarter=3, target_concepts=targets
        )

    def test_refuses_before_deaccumulation(self):
        tools = self._tools()
        verify = next(t for t in tools if t.name == "verify_cash_flow_identity")
        out = verify.invoke({
            "operating_cf": 116996, "investing_cf": -18811,
            "financing_cf": -94575, "net_change": 3610,
        })
        self.assertIn("NOT VERIFIED", out)
        self.assertIn("deaccumulate_cashflow", out)

    def test_allows_after_deaccumulation(self):
        tools = self._tools()
        deacc = next(t for t in tools if t.name == "deaccumulate_cashflow")
        verify = next(t for t in tools if t.name == "verify_cash_flow_identity")
        with mock.patch(
            "earnings_agents.agent.deaccumulate.load_prior_quarter_values",
            return_value={1: 41000.0, 2: 34000.0},
        ):
            deacc.invoke({
                "value": 116996,
                "concept_key": "[us-gaap:NetCashProvidedByUsedInOperatingActivities]",
                "ytd_months": 9,
            })
        out = verify.invoke({
            "operating_cf": 41996, "investing_cf": -18811,
            "financing_cf": -94575, "net_change": 3610,
        })
        self.assertNotIn("NOT VERIFIED", out)


class TestPipelineForcesDeaccumulation(unittest.TestCase):
    """The pipeline must emit a HIGH-severity finding (which blocks the save)
    when the agent reports a YTD cash-flow basis but did not de-accumulate."""

    def _run(self, finalize_result):
        original = pipeline_module.run_agent_loop
        pipeline_module.run_agent_loop = lambda **kw: finalize_result
        sample = (
            "CONDENSED CONSOLIDATED STATEMENTS OF CASH FLOWS (Unaudited)\n"
            "(In millions)\n"
            "Nine Months Ended June 27, 2026\n"
            "Cash generated by operating activities 116,996\n"
        )
        state = {
            "ticker": "AAPL", "company_name": "Apple Inc.",
            "cik": "0000320193", "raw_text": sample,
            "document_map": [{"exhibit": "EX-99.1", "line_start": 1,
                              "line_end": sample.count(chr(10)) + 1}],
            "detected_period": {
                "period_type": "quarterly", "period_end": "2026-06-27",
                "quarter": 3, "period_label": "Three Months Ended June 27, 2026",
                "fiscal_year": 2026,
            },
            "target_statements": ["cashflow"],
            "target_concepts": [
                {
                    "_id": "c1",
                    "concept": "us-gaap:NetCashProvidedByUsedInOperatingActivities",
                    "taxonomy_key": "us-gaap:NetCashProvidedByUsedInOperatingActivities",
                    "label": "Net cash provided by operating activities",
                    "statement_type": "cashflow",
                    "dimension": False, "dimension_concept": False,
                    "calculated": False,
                }
            ],
            "company_industry": {"sic_code": "3571",
                                "sic_description": "Electronic Computers"},
            "recent_concept_ids": [], "calculated_concepts": [], "findings": [],
        }
        try:
            out = pipeline_module._run_extraction_pass(
                state, sample, state["target_concepts"]
            )
        finally:
            pipeline_module.run_agent_loop = original
        return out

    def test_ytd_without_deaccumulation_is_non_blocking_medium_severity(self):
        """Un-deaccumulated flow concepts are omitted from save and never block."""
        out = self._run({
            "__currency__": "USD", "__scale__": "millions",
            "__company_name__": "Apple Inc.", "__evidence__": {},
            "__missing__": "", "__derived__": "",
            "__cashflow_basis__": "ytd_9m",
            "[us-gaap:NetCashProvidedByUsedInOperatingActivities]": 116996,
        })
        cf = [f for f in (out.get("findings") or [])
              if f.get("type") == "cashflow_not_deaccumulated"]
        self.assertEqual(len(cf), 1)
        self.assertEqual(cf[0]["severity"], "medium")
        # Un-deaccumulated flow concept omitted from concept_metrics
        self.assertNotIn("c1", out.get("concept_metrics") or {})

    def test_ytd_with_deaccumulation_is_clean(self):
        out = self._run({
            "__currency__": "USD", "__scale__": "millions",
            "__company_name__": "Apple Inc.", "__evidence__": {},
            "__missing__": "",
            "__derived__": "[us-gaap:NetCashProvidedByUsedInOperatingActivities]",
            "__cashflow_basis__": "ytd_9m",
            "[us-gaap:NetCashProvidedByUsedInOperatingActivities]": 41996,
        })
        cf = [f for f in (out.get("findings") or [])
              if f.get("type") == "cashflow_not_deaccumulated"]
        self.assertEqual(len(cf), 0)
        self.assertIn("c1", out.get("derived_concept_ids") or [])
        self.assertIn("c1", out.get("concept_metrics") or {})

    def test_ytd_omitted_cashflow_basis_detected_from_document_is_medium_severity(self):
        """When the agent forgets to report __cashflow_basis__, the filing's
        'Nine Months Ended' header is used as ground truth and omits raw flow."""
        out = self._run({
            "__currency__": "USD", "__scale__": "millions",
            "__company_name__": "Apple Inc.", "__evidence__": {},
            "__missing__": "", "__derived__": "",
            # __cashflow_basis__ omitted!
            "[us-gaap:NetCashProvidedByUsedInOperatingActivities]": 116996,
        })
        cf = [f for f in (out.get("findings") or [])
              if f.get("type") == "cashflow_not_deaccumulated"]
        self.assertEqual(len(cf), 1)
        self.assertEqual(cf[0]["severity"], "medium")
        self.assertEqual(cf[0]["evidence"]["cashflow_basis"], "ytd_9m")
        self.assertNotIn("c1", out.get("concept_metrics") or {})

    def test_ytd_agent_reported_quarterly_but_document_is_ytd_omits_un_deaccumulated(self):
        """When the agent mistakenly claims quarterly but document is YTD,
        the document ground truth overrules, emits warning, and omits raw flow."""
        out = self._run({
            "__currency__": "USD", "__scale__": "millions",
            "__company_name__": "Apple Inc.", "__evidence__": {},
            "__missing__": "", "__derived__": "",
            "__cashflow_basis__": "quarterly",  # misreported
            "[us-gaap:NetCashProvidedByUsedInOperatingActivities]": 116996,
        })
        cf = [f for f in (out.get("findings") or [])
              if f.get("type") == "cashflow_not_deaccumulated"]
        self.assertEqual(len(cf), 1)
        self.assertEqual(cf[0]["severity"], "medium")
    def test_cashflow_not_deaccumulated_never_blocks_save(self):
        """mongodb_save_node must not fail on cashflow_not_deaccumulated finding."""
        from earnings_agents.nodes.save import mongodb_save_node
        with mock.patch("earnings_agents.integrations.normalize.upsert_concept_values"):
            state = {
                "ticker": "AAPL",
                "company_name": "Apple Inc.",
                "findings": [{
                    "type": "cashflow_not_deaccumulated",
                    "severity": "high",  # Even if high, must not block!
                    "message": "Some concept not de-accumulated",
                }],
                "currency_metadata": {"currency": "USD"},
                "detected_period": {
                    "period_type": "quarterly", "period_end": "2026-06-27",
                    "quarter": 3, "period_label": "Three Months Ended June 27, 2026",
                    "fiscal_year": 2026,
                },
                "concept_metrics": {"c1": 100.0},
                "cik": "0000320193",
            }
            res = mongodb_save_node(state)
            self.assertNotEqual(res.get("status"), "failed")


if __name__ == "__main__":
    unittest.main()
